language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm test
- npm run build
after_success: npm run coverage
before_deploy:
- sed --in-place '/dist/d' .gitignore # Elastic beanstalk uses git deployment and if a file is in the ignore it will not be sent
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: $SECRETACCESSKEY
  region: "us-west-1"
  app: "smarttodo-nest"
  env: "SmarttodoNest-env"
  bucket_name: $BUCKETNAME
  on:
    branch: master