language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm test
after_success: npm run coverage
before_deploy: npm install now --no-save
deploy:
  provider: script # Deploys project to Zeit.co's NOW
  script: now --token $NOW_TOKEN && now alias --token $NOW_TOKEN
  skip_cleanup: true
  on:
    master: true