language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm test
- npm run build
after_success: npm run coverage
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: $SECRETACCESSKEY
  region: "us-west-1"
  app: "smarttodo-nest"
  env: "SmarttodoNest-env"
  bucket_name: $BUCKETNAME
  skip_cleanup: true
  on:
    branch: master